worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    upstream frontend {
        server frontend:5173;
    }

    upstream backend {
        server backend:8080; 
    }

    upstream keycloak {
        server keycloak:8080;
    }

    server {
        listen 80;

        # Route requests to the frontend
        location / {
            proxy_pass http://frontend; 
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            
            # WebSockets support (often needed for modern frontend dev servers)
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

        # Route /api requests to the backend
        location /api/ {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Route /auth requests to Keycloak
        location /auth {
            proxy_pass http://keycloak;
            proxy_set_header Host $host;
            # for Keycloak to log the real client IP instead of Nginx's IP
            proxy_set_header X-Real-IP $remote_addr;
            # for Brute Force protection and logging in Keycloak
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            # for Keycloak to know the original protocol (http or https)
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}