# Initialize the Port
server.port=${BACKEND_PORT:8080}

# Initialize the PostgresSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Automatically create/update database tables
spring.jpa.hibernate.ddl-auto=update

# Read directly from Docker's injected environment variables
keycloak.admin-user=${KEYCLOAK_ADMIN_USER}
keycloak.admin-password=${KEYCLOAK_ADMIN_PASSWORD}

keycloak.server-url=http://keycloak:8080/auth

# Both browser and backend now agree on the exact same issuer identity string
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost/auth/realms/restaurant-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/auth/realms/restaurant-realm/protocol/openid-connect/certs