services:
  db:
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env # Tells Docker to load Master Vault secrets
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile # TODO: build up JAR not done YET
    restart: always
    env_file:
      - .env # Passes the secrets into Spring Boot
    deploy:
      replicas: 3
    depends_on:
      - db
    develop:
      watch:
        - action: sync
          path: ./backend/restaurant/src
          target: /app/src
        - action: rebuild
          path: ./backend/build.gradle.kts

  frontend:
    build: ./frontend
    depends_on:
      - backend
    develop:
      watch:
        - action: sync
          path: ./frontend/restaurant/src
          target: /app/src
        - action: rebuild
          path: ./frontend/package.json

volumes:
  pgdata: