services:
  backend:
    build: 
      context: ./backend/restaurant
      dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - .env # Passes the secrets into Spring Boot
    environment:
      - KEYCLOAK_ADMIN_USER=${KEYCLOAK_ADMIN_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - KEYCLOAK_INTERNAL_URL=${KEYCLOAK_INTERNAL_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_DOCKER_COMPOSE_ENABLED=false
    develop:
      watch:
        - action: sync
          path: ./backend/restaurant/src
          target: /app/src
        - action: rebuild
          path: ./backend/restaurant/build.gradle.kts
    networks:
      - restaurant-network

  frontend:
    build: 
      context: ./frontend/restaurant
      dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - .env # Passes the secrets into Vite
    depends_on:
      - backend
    environment:
      - VITE_KEYCLOAK_URL=${KEYCLOAK_URL}
      - VITE_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - VITE_REALM=${KEYCLOAK_REALM}
    develop:
      watch:
       - action: sync
         path: ./frontend/restaurant/src
         target: /app/src
       - action: sync
         path: ./frontend/restaurant/public
         target: /app/public
       - action: sync
         path: ./frontend/restaurant/index.html
         target: /app/index.html
       - action: rebuild
         path: ./frontend/restaurant/package.json
       - action: rebuild
         path: ./frontend/restaurant/vite.config.ts
    networks:
      - restaurant-network

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    command: start-dev --import-realm --proxy-headers xforwarded # IMPORTANT (running Keycloak behind Nginx)
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME_URL: ${KEYCLOAK_URL}
      KC_HTTP_RELATIVE_PATH: /auth 
      # Sets memory cost to 65536 KB (64 MB) protecting against brute-force attacks (GPU attacks in particular)
      KC_HOSTNAME_STRICT_HTTPS: "false"   # Disables HTTPS requirement for admin
      KC_HOSTNAME_STRICT: "false"
      KC_SPI_PASSWORD_HASHING__ARGON2__MEMORY: 65536
      # Sets parallelism threads to 2
      KC_SPI_PASSWORD_HASHING__ARGON2__PARALLELISM: 2
    volumes: # Persist Keycloak data to avoid losing it when the container restarts
      - keycloak_data:/opt/keycloak/data/
      - ./realm-config.json:/opt/keycloak/data/import/realm.json:ro # Import realm config on startup this is example change it to your actual realm config file
      - ./keycloak-themes/restaurant-theme:/opt/keycloak/themes/restaurant-theme
    networks:
      - restaurant-network

  proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
      - keycloak
    networks:
      - restaurant-network

networks:
  restaurant-network:
    name: my_app_network

volumes:
  keycloak_data:
  pgdata:
