
services:
  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - "${DB_PORT}:5432"
    env_file:
      - .env # Tells Docker to load Master Vault secrets
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - restaurant-network

volumes:
  pgdata:

networks:
  restaurant-network:
    name: my_app_network