parent=keycloak
import=common/keycloak

styles=css/styles.css

# Enable static resource caching for faster page transitions
cacheThemes=true

locales=en

# Suppress the default Keycloak header
kcHtmlClass=login-pf
kcLoginClass=login-pf-page
kcContentWrapperClass=
kcFeedbackAreaClass=
kcFormAreaClass=
